config/routes.rb
Rails.application.routes.draw do

  get '/meetings/new', to: 'meetings#user_new', as: 'new_user_meeting'
  get '/meetings/:id', to: 'meetings#user_show', as: 'user_meeting'
  get '/meetings/:id/edit', to: 'meetings#user_edit', as: 'edit_user_meeting'
  put '/meetings/participate/:id', to: 'meetings#user_update_participate', as: 'update_user_meeting_participate'
  delete '/meetings/participate/:id', to: 'meetings#user_delete_participate', as: 'delete_user_meeting_participate'
  patch '/meetings/:id', to: 'meetings#user_update', as: 'update_user_meeting'
  delete '/meetings/:id', to: 'meetings#user_destroy', as: 'destroy_user_meeting'
  post '/meetings', to: 'meetings#user_create', as: 'create_user_meeting'
  post '/comments', to: 'meetings#create_comment', as: 'create_user_meeting_comment'
  get '/meetings', to: 'meetings#user_index', as: 'user_meetings'

  scope '/api' do
    get '/cities', to: 'cities#api_index', as: 'api_cities'
  end


  get '/search', to: 'pages#search', as: 'search'
  post '/search', to: 'pages#search', as: 'query_search'
  post '/main', to: 'pages#main', as: 'query_main_search'

  scope '/admin' do
    resources :meetings
    resources :interests
    resources :cities
    resources :comments
  end

  get 'admin', to: 'pages#admin'
  get 'main', to: 'pages#main', as: 'main'
  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'

  patch 'profile', to: 'profiles#update', as: 'update_profile'


  root 'pages#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :city
  belongs_to :user
  belongs_to :interest
  has_many :comments
  has_and_belongs_to_many :users

  validates :title, :presence => true
  mount_uploader :image, ImageUploader
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :check_user_is_admin, only: [:show,:edit,:update,:destroy,:new,:index,:create]
  before_action :set_meeting, only: [:show, :user_show, :edit, :user_edit,
                                     :user_update, :update, :destroy,
                                     :user_destroy, :user_update_participate,
                                     :user_delete_participate]
  before_action :set_meetings, only: [:index, :user_index]

  # GET /meetings
  # GET /meetings.json
  def index
  end

  def user_index
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  def user_show
    if user_signed_in?
      @participate = @meeting.users.where(:id => current_user.id)
    end
  end

  def create_comment
    if user_signed_in?
      comment = Comment.new
      comment.text = params[:comment]
      comment.user = current_user
      comment.meeting_id = params[:comment_meeting_id]
      if comment.save
        redirect_to user_meeting_path(params[:comment_meeting_id])
      else
        redirect_to root_path
      end
    end
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    if user_signed_in?
      @meeting.user = current_user
    end
  end

  def user_new
    @meeting = Meeting.new
    if user_signed_in?
      @meeting.user = current_user
      @meeting.city = current_user.city
    end
  end

  # GET /meetings/1/edit
  def edit
  end

  def user_edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    if user_signed_in?
      @meeting.user = current_user
    end

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_create
    @meeting = Meeting.new(meeting_params)
    if user_signed_in?
      @meeting.user = current_user
    end
    if @meeting.save
      redirect_to user_meeting_path(@meeting), notice: 'Meeting was successfully created.'
    else
      render :user_new
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_update
    if @meeting.update(meeting_params)
      redirect_to user_meeting_path(@meeting), notice: 'Meeting was successfully updated.'
    else
      render :edit
    end
  end

  def user_update_participate
    if user_signed_in?
      participate = @meeting.users.where(:id => current_user.id)
      if participate.count == 0
        @meeting.users << current_user
        redirect_to user_meeting_path(@meeting)
      end
    end
  end

  def user_delete_participate
    if user_signed_in?
      participate = @meeting.users.where(:id => current_user.id)
      if participate
        @meeting.users.delete(participate)
        redirect_to user_meeting_path(@meeting)
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_destroy
    if @meeting.user == current_user
      @meeting.destroy
      redirect_to user_meetings_url, notice: 'Meeting was successfully destroyed.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def set_meetings
    @meetings = Meeting.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meeting_params
    params.require(:meeting).permit(:title, :description, :city_id, :user_id, :interest_id, :date_time_start, :date_time_finish, :address, :image)
  end

  def check_user_is_admin
    if current_user
      unless current_user.admin
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true, html: {multipart: true}) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meeting_title, :required => true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :meeting_description %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id , City.order(:title),:id,:title, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :meeting_user_id %>
  </div>

  <div class="field">
    <%= form.label :interest_id %>
    <%= form.collection_select :interest_id , Interest.order(:title),:id,:title, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :date_time_start %>
    <%= form.datetime_select :date_time_start, id: :meeting_date_time_start %>
  </div>

  <div class="field">
    <%= form.label :date_time_finish %>
    <%= form.datetime_select :date_time_finish, id: :meeting_date_time_finish %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :meeting_address %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>City</th>
      <th>User</th>
      <th>Interest</th>
      <th>Date time start</th>
      <th>Date time finish</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.title %></td>
        <td><%= meeting.description %></td>
        <td><%= meeting.city.title if meeting.city %></td>
        <td><%= meeting.user.name if meeting.user %></td>
        <td><%= meeting.interest.title if meeting.interest %></td>
        <td><%= meeting.date_time_start %></td>
        <td><%= meeting.date_time_finish %></td>
        <td><%= meeting.address %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meeting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meeting.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @meeting.city.title if @meeting.city %>
</p>

<p>
  <strong>User:</strong>
  <%= @meeting.user.name if @meeting.user %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @meeting.interest.title if @meeting.interest %>
</p>

<p>
  <strong>Date time start:</strong>
  <%= @meeting.date_time_start %>
</p>

<p>
  <strong>Date time finish:</strong>
  <%= @meeting.date_time_finish %>
</p>

<p>
  <strong>Address:</strong>
  <%= @meeting.address %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/user_edit.html.erb
<div class="main">
  <main class="meeting-create-box container">
    <div class="create-form">
                <span class="title">
                    Создание встречи
                </span>
      <!-- /.title -->
      <%= form_for @meeting, url: update_user_meeting_path, method: :patch,
                   html: {multipart: true, class: 'meeting-create-form'} do |form| %>

        <%= form.label :title, class: 'meeting_name' do %>
          <span class="name">Название:</span>
          <%= form.text_field :title, id: :meeting_title, :required => true %>
        <% end %>

        <%= form.label :description do%><span class="description">Описание:</span>
          <%= form.text_area :description, id: :meeting_description,
                             class: 'meeting-description-field',
                             cols: 30, rows: 10 %>
        <% end %>

        <%= form.label :city_id do %><span>Город:</span>
          <%= form.collection_select :city_id , City.order(:title),:id,:title, include_blank: false %>
        <% end %>

        <%= form.label :interest_id do %><span>Интересы:</span>
          <%= form.collection_select :interest_id , Interest.order(:title),:id,:title, include_blank: false %>
        <% end %>

        <%= form.label :date_time_start, class: 'start-meeting' do %><span>Начало встречи:</span>
          <%= form.datetime_select :date_time_start, id: :meeting_date_time_start %>
        <% end %>

        <%= form.label :date_time_finish, class: 'end-meeting' do %><span>Конец встречи:</span>
          <%= form.datetime_select :date_time_finish, id: :meeting_date_time_finish %>
        <% end %>

        <%= form.label :address do %>
          <span>Адрес:</span>
          <%= form.text_field :address, id: :meeting_address %>
        <% end %>

        <div class="file-upload">

          <%= form.label :image do %>
            <%= form.file_field :image %>
            <span>Выберите файл</span>
          <% end %>

        </div>

        <%= form.submit 'Обновление встречи', class: 'btn-create-meeting'%>

      <% end %>
    </div>
  </main>
</div>

app/views/meetings/user_index.html.erb
<h1>Встречи</h1>
<%= link_to 'Создать встречу', new_user_meeting_path %>
<ul>
  <% @meetings.each do |meeting| %>
    <li><%= link_to meeting.title, user_meeting_path(meeting) %></li>
  <% end %>
</ul>
<%= link_to 'Создать встречу', new_user_meeting_path %>

app/views/meetings/user_new.html.erb
<div class="main">
  <main class="meeting-create-box container">
    <div class="create-form">
                <span class="title">
                    Создание встречи
                </span>
      <!-- /.title -->
      <%= form_for @meeting, url: create_user_meeting_path,
                   html: {multipart: true, class: 'meeting-create-form'} do |form| %>

        <%= form.label :title, class: 'meeting_name' do %>
          <span class="name">Название:</span>
          <%= form.text_field :title, id: :meeting_title, :required => true %>
        <% end %>

        <%= form.label :description do%><span class="description">Описание:</span>
          <%= form.text_area :description, id: :meeting_description,
                             class: 'meeting-description-field',
                             cols: 30, rows: 10 %>
        <% end %>

        <%= form.label :city_id do %><span>Город:</span>
          <%= form.collection_select :city_id , City.order(:title),:id,:title, include_blank: false %>
        <% end %>

        <%= form.label :interest_id do %><span>Интересы:</span>
          <%= form.collection_select :interest_id , Interest.order(:title),:id,:title, include_blank: false %>
        <% end %>

        <%= form.label :date_time_start, class: 'start-meeting' do %><span>Начало встречи:</span>
          <%= form.datetime_select :date_time_start, id: :meeting_date_time_start %>
        <% end %>

        <%= form.label :date_time_finish, class: 'end-meeting' do %><span>Конец встречи:</span>
          <%= form.datetime_select :date_time_finish, id: :meeting_date_time_finish %>
        <% end %>

        <%= form.label :address do %>
          <span>Адрес:</span>
          <%= form.text_field :address, id: :meeting_address %>
        <% end %>

        <div class="file-upload">

          <%= form.label :image do %>
            <%= form.file_field :image %>
            <span>Выберите файл</span>
          <% end %>

        </div>

        <%= form.submit 'Создание встречи', class: 'btn-create-meeting'%>

      <% end %>
    </div>
  </main>
</div>

app/views/meetings/user_show.html.erb
<div class="main">
  <div class="meeting container-small">
    <div class="meeting-box">
      <div class="title-box">
                <span class="title">
                    Встреча - <%= @meeting.title %>
                </span>
      </div>
      <!-- /.title-box -->
      <div class="meeting-event">
        <div class="title-box-event">
          <h2 class="title-event"><%= @meeting.title %></h2>
          <h3 class="description-event"><%= @meeting.interest.title if @meeting.interest %></h3>
        </div>
        <!-- /.title-box-event -->
        <div class="meeting-event__row">
          <div class="col">
            <div class="relation">
              <div class="relation__ratio"></div>
              <!-- /.relation__ratio -->
              <% image = if @meeting.image.file %>
                <% @meeting.image %>
              <% else %>
                <% @meeting.interest.image %>
              <% end %>
              <div class="image-box-event relation__content" style="background-image: url(<%= image %>);">
                <% if user_signed_in? %>
                  <% if @participate.count == 0 %>
                    <%= link_to update_user_meeting_participate_path, :method => :put, :class => 'sign-up-event' do %>
                      <i class="fa fa-plus" aria-hidden="true"></i>  Буду участвовать
                    <% end %>
                  <% else %>
                    <%= link_to delete_user_meeting_participate_path, :method => :delete, :class => 'sign-up-event no-sign-up-event' do %>
                      <i class="fa fa-minus" aria-hidden="true"></i>  Отменить участие
                    <% end %>
                  <% end %>
                <% else %>
                  <%= link_to new_user_session_path, :class => 'sign-up-event' do %>
                    Авторизуйтесь
                  <% end %>
                <% end %>
              </div>
              <!-- /.image-box-event -->
            </div>
            <!-- /.relation -->
          </div>
          <!-- /.col -->
          <div class="col">
            <div class="event-description">
              <div class="date-box">
                <div class="date-start">
                  <span class="date-start__date">31 декабря 2017</span>
                  <!-- /.date-start-text -->
                  <span class="date-start__time">14:00</span>
                  <!-- /.time-start-text -->
                </div>
                <hr>
                <div class="date-end">
                  <span class="date-end__date">31 декабря 2017</span>
                  <!-- /.date-end-text -->
                  <span class="date-end__time">18:00</span>
                  <!-- /.time-end-text -->
                </div>
              </div>
              <!-- /.date-box -->
              <div class="box">
                <div class="text-description-event">

                  <div class="title">
                    <span>Описание встречи</span>
                  </div>
                  <!-- /.title -->
                  <div class="description">
                    <p class="text">
                      <%= @meeting.description %>
                    </p>
                  </div>
                  <!-- /.description -->
                </div>
                <!-- /.text-description -->
                <div class="organizer-box">
                  <a href="#">
                    <%= image_tag 'portrait.png', alt: 'event author portrait', class: 'organizer-image' %>
                  </a>
                  <span class="post">Организатор</span>
                  <span class="organizer-name"><%= @meeting.user.name if @meeting.user %></span>
                </div>
                <!-- /.organizer-box -->
              </div>
              <!-- /.box -->
            </div>
            <!-- /.event-description -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.meeting-box__row -->
        <div class="event-place">
          <div class="box">
                <span class="text">
                    Место проведения встречи
                </span>
            <span class="meeting-place">
                    <b><%= @meeting.city.title if @meeting.city %></b>, <%= @meeting.address %>
                </span>
          </div>
          <!-- /.title-box -->
          <div class="map-image">
            <%= image_tag 'Bitmap.png', alt: 'map', class: 'map' %>
          </div>
          <!-- /.map-image -->
        </div>
        <!-- /.event-place -->
        <div class="meeting-wide-box">
          <div class="col col-left">
            <div class="title-box">
              <span class="title">Участники</span>
            </div>
            <!-- /.title-box -->
            <div class="members-box">
              <div class="members-box__row">
                <% @meeting.users.all.each do |user| %>
                  <div class="members-box__item">
                    <a href="#" class="member-link-profile">
                      <%= image_tag 'portrait.png', :alt => 'Meeting image', :class => 'member-photo' %>
                      <span class="member-name"><%= user.name %></span>
                    </a>
                  </div>
                  <!-- /.members-box__item -->
                <% end %>

              </div>
              <!-- /.members-box__row -->
            </div>
            <!-- /.members-box -->
          </div>
          <div class="col col-right">
            <div class="title-box"><span class="title">Комментарии</span>

            </div>
            <!-- /.title-box -->
            <div class="comments-group">
              <% unless user_signed_in? %>
                <span class="autorization">
                  <%= link_to 'Авторизуйтесь', new_user_session_path, class: 'autorization-link' %>, чтобы оставлять свои комментарии
                </span>
              <% else %>
                <%= form_tag create_user_meeting_comment_path, method: :post, class: 'form-add-comment' do %>
                  <%= text_area_tag :comment, params[:comment],
                                    class: 'field-add-comment', rows: 30, cols: 30, required: true %>
                  <%= hidden_field_tag :comment_meeting_id, @meeting.id %>
                  <%= submit_tag 'Сохранить комментарий', class: 'btn-comment-save' %>
                <% end %>
              <% end %>

              <div class="comments-members">
                <% @meeting.comments.each do |comment| %>
                  <div class="comments-members__item">
                    <div class="image-author">
                      <a href="#" class="member-link-profile">
                        <%= image_tag 'portrait.png', :alt => 'Meeting comment user image' %>
                      </a>
                    </div>
                    <!-- /.image-author -->
                    <div class="comments-text">
                      <a href="#"><span class="name-author-comment"><%= comment.user.name %></span></a>
                      <span class="date-create-comment"><%= comment.created_at %></span>
                      <p class="comment-field">
                        <%= comment.text %>
                      </p>
                      <!-- /.comment-text -->
                    </div>
                    <!-- /.comments-text -->
                  </div>
                  <!-- /.comments__item -->
                <% end %>
              </div>
              <!-- /.comments -->
            </div>
            <!-- /.comments-box -->
          </div>
        </div>
        <!-- /.meeting-wide-box -->
      </div>
      <!-- /.meeting-box -->
    </div>
    <!-- /. -->
  </div>
  <!-- /.meeting -->
</div>
<!-- /.main -->