config/routes.rb
Rails.application.routes.draw do

  get '/meetings/new', to: 'meetings#user_new', as: 'new_user_meeting'
  get '/meetings/:id', to: 'meetings#user_show', as: 'user_meeting'
  get '/meetings/:id/edit', to: 'meetings#user_edit', as: 'edit_user_meeting'
  put '/meetings/participate/:id', to: 'meetings#user_update_participate', as: 'update_user_meeting_participate'
  delete '/meetings/participate/:id', to: 'meetings#user_delete_participate', as: 'delete_user_meeting_participate'
  patch '/meetings/:id', to: 'meetings#user_update', as: 'update_user_meeting'
  delete '/meetings/:id', to: 'meetings#user_destroy', as: 'destroy_user_meeting'
  post '/meetings', to: 'meetings#user_create', as: 'create_user_meeting'
  post '/comments', to: 'meetings#create_comment', as: 'create_user_meeting_comment'
  get '/meetings', to: 'meetings#user_index', as: 'user_meetings'

  scope '/api' do
    get '/cities', to: 'cities#api_index', as: 'api_cities'
  end


  get '/search', to: 'pages#search', as: 'search'
  post '/search', to: 'pages#search', as: 'query_search'
  post '/main', to: 'pages#main', as: 'query_main_search'

  scope '/admin' do
    resources :meetings
    resources :interests
    resources :cities
    resources :comments
  end

  get 'admin', to: 'pages#admin'
  get 'main', to: 'pages#main', as: 'main'
  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'

  patch 'profile', to: 'profiles#update', as: 'update_profile'


  root 'pages#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<h1>Администрирование</h1>
<ul>
  <li><%= link_to 'Города', cities_path %></li>
  <li><%= link_to 'Интересы', interests_path %></li>
  <li><%= link_to 'Встречи', meetings_path %></li>
  <li><%= link_to 'Комментарии', comments_path %></li>
</ul>

app/views/pages/index.html.erb
<div class="main">
  <div class="image-map-box container">
    <%= image_tag 'map2.png', alt: 'image map', class: 'image-map' %>
    <%= link_to 'Начать работу', main_path, class: 'start-link container' %>
  </div>

</div>
<!-- /.main -->

app/views/pages/main.html.erb
<div class="main">
  <div class="content-inner container">
    <div class="col col_left">
      <div class="title-box">
        <span class="title">Поиск событий</span>
      </div>
      <!-- /.title-box -->
      <div class="find-events-box">
        <%= search_form_for @search, url: query_main_search_path, html: { method: :post } do |f| %>
          <p class="title">Ключевые слова</p>
          <%= f.label :title_or_description_cont do %>
            <%= f.search_field :title_or_description_cont, :class => 'find-input' %>
          <% end %>

          <p class="title">Город</p>
          <%= f.label :city_id_eq do %>
            <%= f.search_field :city_title_eq, :class => 'find-input', :list => 'city_datalist', :autocomplete => false %>
            <datalist id="city_datalist">
              <% City.all.each do |city| %>
                <option value="<%= city.title %>"></option>
              <% end %>
            </datalist>
          <% end %>
          <%= f.submit 'Поиск', :class => 'find-btn' %>
        <% end %>
      </div>
      <!-- /.find-events-box -->
    </div>
    <!-- /.content-inner__col_left -->
    <div class="col col_right">
      <div class="title-box">
        <span class="title">События</span>
        <span class="create-event">
          <%= link_to 'Создать', new_user_meeting_path, class: 'create-event-link' %>
        </span>
        <a href="#" class="th-link">
          <%= image_tag 'Shape.png', alt: 'List' %>
        </a>
        <a href="#" class="map-link">
          <%= image_tag 'map.png', alt: 'Map' %>
        </a>
      </div>
      <!-- /.title-box -->
      <div class="events">


        <% @meets.each do |meet| %>

          <div class="events__item">
            <%= link_to user_meeting_path(meet) do %>
              <% if meet.image.file %>
                <div style="background-image: url(<%= image_url meet.image %>); background-size: cover" class="events__item__img"></div>
              <% else %>
                <div style="background-image: url(<%= image_url meet.interest.image %>); background-size: cover" class="events__item__img"></div>
              <% end %>
            <% end %>
            <div class="events__item__text">
              <h2 class="event-title"><%= meet.title %></h2>
              <span class="event-description"><%= meet.description %></span>
              <time datetime="<%= meet.date_time_start %>" class="event-date"><%= meet.date_time_start %></time>
              <span class="event-place"><%= meet.city.title if meet.city %>, <%= meet.address %></span>
            </div>
            <a href="#" class="events__item__img-account">
              <%= image_tag 'portrait.png', alt: 'event author portrait', class: 'portrait' %>
              <span class="name"><%= meet.user.name %></span>
            </a>
          </div>
          <!-- /.events__item -->

        <% end %>

      </div>
      <!-- /.events -->
    </div>
    <!-- /.content-inner__col_right -->
  </div>

  <!-- /.content-inner container -->
</div>
<!-- /.main -->

app/views/pages/profile.html.erb
<h1>Мой профиль</h1>
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.city.title %></p>
<p>Зарегистрирован  <%= @user.created_at %></p>
<br>
<p>Последний вход в систему <%= @user.last_sign_in_at %> с адреса <%= @user.last_sign_in_ip %></p>

app/views/pages/search.html.erb
<h1>Поиск</h1>
<%= search_form_for @search, url: query_search_path, method: :post do |f| %>

  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>

  <%= f.submit %>

<% end %>

<% if @meetings %>
  <ul>
    <% @meetings.each do |meet| %>
      <li>
        <%= meet.title %>
      </li>
    <% end %>
  </ul>
<% end %>