config/routes.rb
Rails.application.routes.draw do

  get '/meetings/new', to: 'meetings#user_new', as: 'new_user_meeting'
  get '/meetings/:id', to: 'meetings#user_show', as: 'user_meeting'
  get '/meetings/:id/edit', to: 'meetings#user_edit', as: 'edit_user_meeting'
  put '/meetings/participate/:id', to: 'meetings#user_update_participate', as: 'update_user_meeting_participate'
  delete '/meetings/participate/:id', to: 'meetings#user_delete_participate', as: 'delete_user_meeting_participate'
  patch '/meetings/:id', to: 'meetings#user_update', as: 'update_user_meeting'
  delete '/meetings/:id', to: 'meetings#user_destroy', as: 'destroy_user_meeting'
  post '/meetings', to: 'meetings#user_create', as: 'create_user_meeting'
  post '/comments', to: 'meetings#create_comment', as: 'create_user_meeting_comment'
  get '/meetings', to: 'meetings#user_index', as: 'user_meetings'

  scope '/api' do
    get '/cities', to: 'cities#api_index', as: 'api_cities'
  end


  get '/search', to: 'pages#search', as: 'search'
  post '/search', to: 'pages#search', as: 'query_search'
  post '/main', to: 'pages#main', as: 'query_main_search'

  scope '/admin' do
    resources :meetings
    resources :interests
    resources :cities
    resources :comments
  end

  get 'admin', to: 'pages#admin'
  get 'main', to: 'pages#main', as: 'main'
  get 'profile', to: 'profiles#show', as: 'profile'
  get 'profile/edit', to: 'profiles#edit', as: 'edit_profile'

  patch 'profile', to: 'profiles#update', as: 'update_profile'


  root 'pages#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/interest.rb
class Interest < ApplicationRecord
  validates :title, :presence => true
  mount_uploader :image, ImageUploader
  has_many :meetings
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  before_action :check_user_is_admin
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_interest
    @interest = Interest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def interest_params
    params.require(:interest).permit(:title, :description, :image)
  end

  def check_user_is_admin
    if current_user
      unless current_user.admin
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_with(model: interest, local: true) do |form| %>
  <% if interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :interest_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :interest_description %>
  </div>

  <div class="field">
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.title %></td>
        <td><%= interest.description %></td>
        <td><%= interest.image %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @interest.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @interest.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @interest.image %>
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>